#ifndef BAR_H
#define BAR_H

#include "EntertainmentBuilding.h"

/**
 * @class Bar
 * @brief Represents a bar establishment in the entertainment district
 *
 * The Bar class is a specialized type of EntertainmentBuilding that generates
 * revenue and has associated consumption costs.
 */
class Bar : public EntertainmentBuilding
{
private:
    int revenue; /**< The revenue generated by the bar */

public:
    Bar(int revenue, int consumption, int x, int y) : EntertainmentBuilding("Bar", x, y) {}
};
#endif