#ifndef COMMERCIALBUILDING_H
#define COMMERCIALBUILDING_H

#include "Building.h"

/**
 * @brief Class representing a commercial building in the simulation
 *
 * CommercialBuilding extends the Building base class to implement
 * specific functionality for commercial properties, including
 * revenue generation and resource consumption.
 */
class CommercialBuilding : public Building
{
private:
	int revenue; ///< Revenue generated by the building

public:
	/**
	 * @brief Get cost consumption for commercial building
	 * @return Cost consumption value
	 */
	virtual int getCostConsumption() override;

	/**
	 * @brief Get revenue generated by commercial building
	 * @return Revenue value
	 */
	virtual int getRevenue() override;

	/**
	 * @brief Get sewage production for commercial building
	 * @return Sewage production value
	 */
	virtual int getSewageProduction() override;

	/**
	 * @brief Get waste production for commercial building
	 * @return Waste production value
	 */
	virtual int getWasteProduction() override;
};

#endif