#ifndef INDUSTRIALBUILDING_H
#define INDUSTRIALBUILDING_H

#include "Building.h"

/**
 * @brief Class representing an industrial building in the simulation
 *
 * IndustrialBuilding extends the Building base class to implement
 * specific functionality for industrial properties, with focus on
 * waste production and resource management.
 */
class IndustrialBuilding : public Building
{
private:
	int wasteProduction; ///< Rate of waste production

public:
	IndustrialBuilding(std::string name, int x, int y) : Building(name, x, y) {}

	/**
	 * @brief Get cost consumption for industrial building
	 * @return Cost consumption value
	 */
	virtual int getCostConsumption() override;

	/**
	 * @brief Get revenue generated by industrial building
	 * @return Revenue value
	 */
	virtual int getRevenue() override;

	/**
	 * @brief Get sewage production for industrial building
	 * @return Sewage production value
	 */
	virtual int getSewageProduction() override;

	/**
	 * @brief Get waste production for industrial building
	 * @return Waste production value
	 */
	virtual int getWasteProduction() override;
};

#endif