#ifndef POWER_H
#define POWER_H

#include "PlantBuilding.h"

/**
 * @class Power
 * @brief Represents a power plant building in the city
 *
 * The Power class is a specialized type of PlantBuilding that generates
 * electricity for the city's infrastructure and buildings. It manages
 * power production rates and associated operational aspects.
 */
class Power : public PlantBuilding
{
private:
    int powerProduction; /**< The amount of power generated by the plant */

public:
    Power(int x, int y) : PlantBuilding("Power", x, y) {}
    
    /**
     * @brief Gets the current power production rate
     * @return The amount of power being produced by the plant
     */
    int getPowerProduction() { return powerProduction; }
};

#endif