#ifndef RESIDENTIALBUILDING_H
#define RESIDENTIALBUILDING_H

#include "Building.h"

/**
 * @brief A class representing residential buildings in the city
 * @details ResidentialBuilding is derived from the Building base class and implements
 *          functionality specific to residential structures such as houses and apartments
 */
class ResidentialBuilding : public Building
{
private:
	/** @brief The amount of waste produced by the residential building */
	int wasteProduction;

public:
	ResidentialBuilding(std::string name, int x, int y) : Building(name, x, y) {}

	/**
	 * @brief Gets the cost consumption of the residential building
	 * @return The cost consumption value as an integer
	 */
	virtual int getCostConsumption() override;

	/**
	 * @brief Gets the revenue generated by the residential building
	 * @return The revenue value as an integer
	 */
	virtual int getRevenue() override;

	/**
	 * @brief Gets the waste production of the residential building
	 * @return The waste production value as an integer
	 */
	virtual int getWasteProduction() override;
};

#endif