#ifndef THEATER_H
#define THEATER_H

#include "EntertainmentBuilding.h"

/**
 * @class Theater
 * @brief Represents a theater in the entertainment district
 *
 * The Theater class is a specialized type of EntertainmentBuilding that provides
 * cultural and entertainment services to citizens. It generates revenue through
 * performances and has associated operational costs.
 */
class Theater : public EntertainmentBuilding
{
private:
    int revenue; /**< The revenue generated by the theater */

public:
    /**
     * @brief Constructs a new Theater instance
     * @param revenue Initial revenue value for the theater
     * @param consumption Initial consumption value for operating costs
     */
    Theater(int revenue, int consumption);
};
#endif